[package]
name = "auto-classi-for-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
headless_chrome = {git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = ["fetch"]}
